const IMAGES = {
	logo: new URL("./logo/logo.svg", import.meta.url).href,
	photo: new URL("./photo/sandra.webp", import.meta.url).href,
	avatar: new URL("./photo/avatar.webp", import.meta.url).href,
	about: new URL("./about/ID-Card.webp", import.meta.url).href,

	portfolio: new URL("./projects/portfolio/portfolio.webp", import.meta.url),
	folder: new URL("./projects/folder.webp", import.meta.url),
	// PROJECTS
	app: new URL("./projects/app/app.webp", import.meta.url),
	appTaxi: new URL("./projects/app/taxi.webp", import.meta.url),
	appTienda: new URL("./projects/app/tienda.webp", import.meta.url),
	puridiom: new URL("./projects/puridiom/puridiom.webp", import.meta.url),
	puridiomBack: new URL("./projects/puridiom/back.webp", import.meta.url),
	puridiomDetails: new URL("./projects/puridiom/details.webp", import.meta.url),
	puridiomStep1: new URL("./projects/puridiom/step1.webp", import.meta.url),
	puridiomStep2: new URL("./projects/puridiom/step2.webp", import.meta.url),
	puridiomStep3: new URL("./projects/puridiom/step3.webp", import.meta.url),
	puridiomStep4: new URL("./projects/puridiom/step4.webp", import.meta.url),
	puridiomStep5: new URL("./projects/puridiom/step5.webp", import.meta.url),
	puridiomStep6: new URL("./projects/puridiom/step6.webp", import.meta.url),
	puridiomStep7: new URL("./projects/puridiom/step7.webp", import.meta.url),
	puridiomStep8: new URL("./projects/puridiom/step8.webp", import.meta.url),
	puridiomStep9: new URL("./projects/puridiom/step9.webp", import.meta.url),
	puridiomStep10: new URL("./projects/puridiom/step10.webp", import.meta.url),
	yaykuy: new URL("./projects/yaykuy/yaykuy.webp", import.meta.url),
	yaykuyBack: new URL("./projects/yaykuy/back.webp", import.meta.url),
	yaykuyDetails: new URL("./projects/yaykuy/details.webp", import.meta.url),
	yaykuyStep1: new URL("./projects/yaykuy/step1.webp", import.meta.url),
	yaykuyStep2: new URL("./projects/yaykuy/step2.webp", import.meta.url),
	yaykuyStep3: new URL("./projects/yaykuy/step3.webp", import.meta.url),
	yaykuyStep4: new URL("./projects/yaykuy/step4.webp", import.meta.url),
	yaykuyStep5: new URL("./projects/yaykuy/step5.webp", import.meta.url),
	yaykuyStep6: new URL("./projects/yaykuy/step6.webp", import.meta.url),
	yaykuyStep7: new URL("./projects/yaykuy/step7.webp", import.meta.url),
	akar: new URL("./projects/akar/akar.webp", import.meta.url),
	akarBack: new URL("./projects/akar/back.webp", import.meta.url),
	akarDetails: new URL("./projects/akar/details.webp", import.meta.url),
	akarStep1: new URL("./projects/akar/step1.webp", import.meta.url),
	akarStep2: new URL("./projects/akar/step2.webp", import.meta.url),
	akarStep3: new URL("./projects/akar/step3.webp", import.meta.url),
	akarStep4: new URL("./projects/akar/step4.webp", import.meta.url),
	akarStep5: new URL("./projects/akar/step5.webp", import.meta.url),
};
export default IMAGES;
